# Copyright (c) MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: release
# generating and publishing release package artifacts from the main branch

on:
  workflow_dispatch:
    inputs:
        tag:
          description: 'Tag of MONAILabel'
          required: true
          default: '0.8.5'

jobs:
  packaging:
    runs-on: ubuntu-latest
    env:
      MONAI_ZOO_AUTH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Cache for pip
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cache/pip
            ~/.cache/torch
          key: ${{ runner.os }}-pip-${{ steps.pip-cache.outputs.datew }}
      - name: Install dependencies
        run: |
          rm -rf /opt/hostedtoolcache
          sudo apt-get install openslide-tools -y
          python -m pip install --user --upgrade pip setuptools wheel
          python -m pip install torch torchvision
      - name: Clone MONAILabel
        run: |
            git clone https://github.com/Project-MONAI/MONAILabel.git
            cd MONAILabel
            git checkout ${{ github.event.inputs.tag }}
      - name: Patch with Databricks Integration
        run: |
            cd MONAILabel
            cp ../monailabel_datastore_databricks_client.py monailabel/datastore/databricks_client.py
            cp ../plugins/ohifv3/build.sh plugins/ohifv3/build.sh
            git apply --reject --whitespace=fix ../monailabel_config.py.patch
            git apply --reject --whitespace=fix ../monailabel_datastore_dicom.py.patch
            git apply --reject --whitespace=fix ../monailabel_datastore_utils_dicom.py.patch
            git apply --reject --whitespace=fix ../monailabel_interfaces_app.py.patch
            git apply --reject --whitespace=fix ../monailabel_main.py.patch
            git apply --reject --whitespace=fix ../monailabel_requirements.txt.patch
            echo "Patching completed"
      - name: Build Package
        run: |
          cd MONAILabel
          ./runtests.sh --clean
          BUILD_OHIF=true python setup.py sdist bdist_wheel --build-number $(date +'%Y%m%d%H%M')
          ls -l dist
      - name: Verify Package
        run: |
          cd MONAILabel
          tmp_dir=$(mktemp -d)
          cp dist/monailabel* "$tmp_dir"
          rm -r build monailabel*.egg-info

          # install from wheel
          python -m pip install pydicom==2.4.4 itk==5.4.3 "$tmp_dir"/monailabel*.whl
          python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
          python -c 'import monailabel; print(monailabel.__file__)'

          # install test utilities
          python -m pip install pytest

          # start the monailabel server in the background and run the integration tests
          ./runtests.sh --net

          # cleanup
          python -m pip uninstall -y monailabel
          rm -r "$tmp_dir"
        env:
          shell: bash

      - name: Upload ohif artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ohif-${{ github.event.inputs.tag }}
          path: MONAILabel/monailabel/endpoints/static/ohif/

      - name: Upload monailabel artifacts
        uses: actions/upload-artifact@v4
        with:
            name: monailabel-${{ github.event.inputs.tag }}.whl
            path: MONAILabel/dist/monailabel*.whl

